[envs.default]
dependencies = [
  "robotcode-runner",
  "pytest",
  "pytest-html",
  "pytest-cov",
  "mypy",
  "ruff",
  "black",
  "GitPython",
  "semantic-version",
]

[envs.default.scripts]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=JavaLibraryBase --cov=tests {args}"
no-cov = "cov --no-cov {args}"
test-py = "pytest {args}"
test-robot = "robotcode run {args}"
test = ["test-py", "test-robot"]

[envs.rfmaster]
python = "3.11"
extra-dependencies = [
  "robotframework @ git+https://github.com/robotframework/robotframework.git",
]

[envs.py312_rfmaster]
python = "3.12"
extra-dependencies = [
  "robotframework @ git+https://github.com/robotframework/robotframework.git",
]

[envs.rfdevel]
python = "3.11"
post-install-commands = ["pip install -U -e {root:uri}/../robotframework"]

[envs.devel]
python = "3.8"

[[envs.devel.matrix]]
python = ["3.8", "3.9", "3.10", "3.11"]
rf = ["rf41", "rf50", "rf60", "rf61b1"]

[envs.devel.overrides]
matrix.rf.dependencies = [
  { value = "robotframework>=4.1.0, <5.0", if = [
    "rf41",
  ] },
  { value = "robotframework>=5.0.0, <6.0", if = [
    "rf50",
  ] },
  { value = "robotframework>6.0.0, <6.1", if = [
    "rf60",
  ] },
  { value = "robotframework==6.1b1", if = [
    "rf61b1",
  ] },
]

[[envs.test.matrix]]
rf = ["rf41", "rf50", "rf60", "rf61b1"]

[envs.test.overrides]
matrix.rf.dependencies = [
  { value = "robotframework>=4.1.0, <5.0", if = [
    "rf41",
  ] },
  { value = "robotframework>=5.0.0, <6.0", if = [
    "rf50",
  ] },
  { value = "robotframework>6.0.0, <6.1", if = [
    "rf60",
  ] },
  { value = "robotframework==6.1b1", if = [
    "rf61b1",
  ] },
]

[envs.lint]
#skip-install = true


[envs.lint.scripts]
typing = ["mypy --install-types --non-interactive {args:.}"]
style = ["ruff .", "black --check --diff ."]
fmt = ["black .", "ruff --fix .", "style"]
all = ["style", "typing"]

[envs.pages]
#detached = true
extra-dependencies = [
  "mkdocs>=1.4.2",
  "mkdocs-material",
  # Plugins
  "mkdocs-minify-plugin",
  "mkdocs-git-revision-date-localized-plugin",
  "mkdocstrings-python",
  "mkdocs-redirects",
  "mkdocs-glightbox",

  # Extensions
  "mkdocs-click~=0.8.0",
  "pymdown-extensions~=9.6.0",
  # Necessary for syntax highlighting in code blocks
  "pygments",
  "mike",
]

[envs.pages.scripts]
build = ["mkdocs build"]
deploy = ["python scripts/deploy_docs.py"]


[envs.build]
skip-install = true
detached = true
python = "38"
dependencies = ["GitPython", "semantic-version"]

[envs.build.scripts]
update-git-versions = ["python scripts/update_git_versions.py"]
update-doc-links = ["python scripts/update_doc_links.py"]
package = ["python scripts/package.py"]
publish = ["python scripts/publish.py"]
extract-release-notes = ["python scripts/extract_release_notes.py"]
is-prerelease = ["python scripts/is_prerelease.py"]
